# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 16:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supp_city_id', models.CharField(blank=True, max_length=50, null=True)),
                ('supp_city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('supp_dest_code', models.CharField(blank=True, max_length=50, null=True)),
                ('supp_dest_name', models.CharField(blank=True, max_length=50, null=True)),
                ('supp_country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('grn_city_code', models.CharField(blank=True, max_length=50, null=True)),
                ('grn_city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('grn_dest_code', models.CharField(blank=True, max_length=50, null=True)),
                ('grn_dest_name', models.CharField(blank=True, max_length=100, null=True)),
                ('grn_country_code', models.CharField(blank=True, max_length=50, null=True)),
                ('grn_country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Not Verfied'), (1, 'Verfied'), (2, 'Rejected')], default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
