# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20171108_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymapping',
            name='supp_country_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
